<?php
/**
 * Created by PhpStorm.
 * User: yusida
 * Date: 2/16/17
 * Time: 3:00 PM
 */

namespace Modules\Villamanager\Repositories\Eloquent;


use Modules\Core\Repositories\Eloquent\EloquentBaseRepository;
use Modules\Villamanager\Events\CategoryWasCreated;
use Modules\Villamanager\Events\CategoryWasDeleted;
use Modules\Villamanager\Events\CategoryWasUpdated;
use Modules\Villamanager\Repositories\CategoryRepository;

class EloquentCategoryRepository extends EloquentBaseRepository implements CategoryRepository
{
    public function create($data)
    {
        $category = parent::create($data); // TODO: Change the autogenerated stub
        event(new CategoryWasCreated($category, $data));
        return $category;
    }

    public function update($model, $data)
    {
        $category = parent::update($model, $data); // TODO: Change the autogenerated stub
        event(new CategoryWasUpdated($category,$data));
        return $category;
    }

    public function destroy($model)
    {
        event(new CategoryWasDeleted($model->id, get_class($model)));
        return parent::destroy($model); // TODO: Change the autogenerated stub
    }
}